version: "3.3"

services:
    db:
        image: postgres
        environment: 
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: league_replica
        volumes:
            - ./db_data:/var/lib/postgresql/data
        ports:
            - "54322:5432"


